workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Clean CocoaPods and Xcode cache
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ios/Pods
          rm -rf ios/.symlinks
          rm -rf ios/Podfile.lock
      - name: Downgrade xcodeproj
        script: |
          gem uninstall xcodeproj
          gem install xcodeproj --version=1.25.0
      - name: Install iOS dependencies
        script: |
          cd ios
          pod deintegrate
          pod cache clean --all
          pod install --repo-update
      - name: Build iOS simulator app (verbose)
        script: |
          flutter build ios --simulator --verbose
      - mkdir -p build/ios/ipa
      - zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app
    artifacts:
      - build/ios/ipa/Runner.app.zip