workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Check CocoaPods and xcodeproj versions
        script: |
          echo "Checking CocoaPods version"
          pod --version
          echo "Checking xcodeproj version"
          gem list xcodeproj
      - name: Downgrade xcodeproj
        script: |
          gem uninstall xcodeproj
          gem install xcodeproj --version=1.25.0
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS simulator app (verbose)
        script: |
          flutter build ios --simulator --verbose
      # Удаляем шаг генерации локализации
      # - name: Generate localization files
      #   script: |
      #     flutter gen-l10n
      # - flutter build ios --release --no-codesign # Комментируем релизный билд
      - mkdir -p build/ios/ipa # Шаги для упаковки
      - zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app # Шаги для упаковки
    artifacts:
      - build/ios/ipa/Runner.app.zip