workflows:
  ios-release-no-shorebird:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS simulator app
        script: |
          flutter build ios --simulator
      # Удаляем шаг генерации локализации
      # - name: Generate localization files
      #   script: |
      #     flutter gen-l10n
      # - flutter build ios --simulator # Удаляем дублирующийся build шаг
      # - mkdir -p build/ios/ipa # Оставляем эти шаги для упаковки
      # - zip -r build/ios/ipa/Runner.app.zip build/ios/iphonesimulator/Runner.app # Оставляем эти шаги для упаковки
    artifacts:
      - build/ios/ipa/Runner.app.zip
